const std = @import("std");

pub fn main(init: std.process.Init) !void {
    var args = try init.minimal.args.iterateAllocator(init.arena.allocator());

    _ = args.next();

    const input_dir = args.next() orelse return error.InputDirectory;
    const zig_exe = args.next() orelse return error.ZigExeMissing;
    const output_dir_path = args.next() orelse return error.OutputDirectoryMissing;

    var cwd = std.Io.Dir.cwd();

    // Open output dir
    var output_dir = cwd.openDir(init.io, output_dir_path, .{ .access_sub_paths = true }) catch |e| {
        std.log.err("output dir {s} not found", .{output_dir_path});
        return e;
    };
    defer output_dir.close(init.io);

    // Copy from input to output dir
    {
        // Open the directory we want to patch
        var to_patch_dir = cwd.openDir(init.io, input_dir, .{
            .access_sub_paths = true,
            .follow_symlinks = false,
            .iterate = true,
        }) catch |e| {
            std.log.err("to patch dir not found {}", .{e});
            return e;
        };
        defer to_patch_dir.close(init.io);

        var to_patch_it = try to_patch_dir.walkSelectively(init.gpa);
        defer to_patch_it.deinit();

        while (try to_patch_it.next(init.io)) |entry| {
            switch (entry.kind) {
                .directory => {
                    output_dir.createDirPath(init.io, entry.path) catch |e| {
                        std.log.err("createDirPath {s} failed {}", .{ entry.path, e });
                        return e;
                    };

                    try to_patch_it.enter(init.io, entry);
                },
                .file => {
                    to_patch_dir.copyFile(entry.path, output_dir, entry.path, init.io, .{ .make_path = true }) catch |e| {
                        std.log.err("copyFile {s} failed {}", .{ entry.path, e });
                        return e;
                    };
                },
                else => continue,
            }
        }
    }

    // Fmt output
    {
        const res = try std.process.run(init.arena.allocator(), init.io, .{
            .argv = &.{ zig_exe, "fmt", output_dir_path },
        });
        if (res.term != .exited or res.term.exited != 0) {
            return error.FailedToZigFmt;
        }
    }

    const child_dir = try std.Io.Dir.cwd().openDir(init.io, output_dir_path, .{ .iterate = true });
    var content: std.ArrayList(u8) = .empty;

    const DirStackEntry = struct {
        path: []const u8,
        entry: std.Io.Dir,
    };
    var dir_stack: std.ArrayList(DirStackEntry) = .empty;
    try dir_stack.append(init.arena.allocator(), .{ .path = "", .entry = child_dir });

    // Find exports inside the generated proto files
    var exports: std.ArrayList([]const u8) = .empty;
    while (dir_stack.items.len > 0) {
        const next_child = dir_stack.pop() orelse @panic("");
        var it = next_child.entry.iterate();
        while (try it.next(init.io)) |next| {
            switch (next.kind) {
                .file => {
                    const child_content = try next_child.entry.readFileAlloc(init.io, next.name, init.arena.allocator(), .unlimited);

                    const export_prefix = "pub const ";

                    var exported_members = std.mem.splitScalar(u8, child_content, '\n');
                    while (exported_members.next()) |line| {
                        if (!std.mem.startsWith(u8, line, export_prefix)) {
                            continue;
                        }

                        const end = std.mem.indexOfScalar(u8, line[export_prefix.len..], ' ') orelse {
                            return error.CorruptExport;
                        };

                        const type_name = line[export_prefix.len .. export_prefix.len + end];
                        const export_line = try std.fmt.allocPrint(init.arena.allocator(), "pub const {s} = @import(\"{s}{s}\").{s};", .{ type_name, next_child.path, next.name, type_name });
                        try exports.append(init.arena.allocator(), export_line);
                    }
                },
                .directory => {
                    const dir = try next_child.entry.openDir(init.io, next.name, .{ .iterate = true });
                    const path = try std.mem.concat(init.arena.allocator(), u8, &.{ next_child.path, next.name, "/" });

                    try dir_stack.append(init.arena.allocator(), .{
                        .entry = dir,
                        .path = path,
                    });
                },
                else => {},
            }
        }
    }

    // Build content
    try content.appendSlice(init.arena.allocator(), "// Code generated by protoc-gen-zig\n");

    for (exports.items) |export_line| {
        try content.appendSlice(init.arena.allocator(), export_line);
        try content.append(init.arena.allocator(), '\n');
    }

    try output_dir.writeFile(init.io, .{
        .sub_path = "api.zig",
        .data = content.items,
    });
}
